security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN_BAGIAN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN_BAGIAN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
            logout:       true
            anonymous:    true
            remember_me:
                secret:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~

    access_control:
        - { path: ^/bundles*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/img*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fonts*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/plugins*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: [ROLE_USER, IS_AUTHENTICATED_FULLY] }
        - { path: ^/, role: [ROLE_USER, IS_AUTHENTICATED_FULLY] }